# ===============================================================================================
# DEVELOPMENT PROFILE
# File cấu hình dành riêng cho môi trường Development (Local/Dev)
# ===============================================================================================

# -----------------------------------------------------------------------------------------------
# 1. DATA PERSISTENCE, MESSAGING & IDENTITY
# -----------------------------------------------------------------------------------------------
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quasar_platform?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: localhost
      port: 6379

# -----------------------------------------------------------------------------------------------
# 2. EXTERNAL SERVICES & CUSTOM APP PROPERTIES
# -----------------------------------------------------------------------------------------------
jwt:
  secretKey: ${JWT_SECRET_DEV}
  expiration: 3600000
  expiration-refresh-token: 2592000000

aws:
  s3:
    bucket: ${AWS_S3_BUCKET_DEV}
    region: ${AWS_S3_REGION_DEV}
    access: ${AWS_ACCESS_KEY_DEV}
    secret: ${AWS_SECRET_KEY_DEV}

vnpay:
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "http://localhost:4200/payments/payment-callback"
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
  tmn-code: ${VNPAY_TMN_CODE_DEV}
  secret-key: ${VNPAY_SECRET_KEY_DEV}

sendgrid:
  api-key: ${SENDGRID_API_KEY_DEV}
  from-email: ${SENDGRID_FROM_EMAIL_DEV}

# -----------------------------------------------------------------------------------------------
# 3. LOGGING & DIAGNOSTICS
# -----------------------------------------------------------------------------------------------
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
