# ===============================================================================================
# PRODUCTION PROFILE
# File cấu hình dành riêng cho môi trường Production (Môi trường thực tế)
# ===============================================================================================

# -----------------------------------------------------------------------------------------------
# 1. DATA PERSISTENCE, MESSAGING & IDENTITY
# -----------------------------------------------------------------------------------------------
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE}
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

# -----------------------------------------------------------------------------------------------
# 2. EXTERNAL SERVICES & CUSTOM APP PROPERTIES
# -----------------------------------------------------------------------------------------------
jwt:
  secretKey: ${JWT_SECRET_PROD}
  expiration: 3600000
  expiration-refresh-token: 2592000000

aws:
  s3:
    bucket: ${AWS_S3_BUCKET_PROD}
    region: ${AWS_S3_REGION_PROD}
    access: ${AWS_ACCESS_KEY_PROD}
    secret: ${AWS_SECRET_KEY_PROD}

vnpay:
  pay-url: "https://pay.vnpayment.vn/vpcpay.html"
  return-url: ${VNPAY_RETURN_URL_PROD}
  api-url: "https://pay.vnpayment.vn/merchant_webapi/api/transaction"
  tmn-code: ${VNPAY_TMN_CODE_PROD}
  secret-key: ${VNPAY_SECRET_KEY_PROD}

sendgrid:
  api-key: ${SENDGRID_API_KEY_PROD}
  from-email: ${SENDGRID_FROM_EMAIL_PROD}

# -----------------------------------------------------------------------------------------------
# 3. OPERATIONAL LOGGING & MONITORING
# -----------------------------------------------------------------------------------------------
logging:
  level:
    root: INFO
    org.springframework.security: INFO
